### ISSUE TITLE
Translation "вікна, риба". venv.html#how-venvs-work

### ISSUE THREAD

**Issue by lexsysko** [python/python-docs-uk#13]
https://docs.python.org/uk/3/library/venv.html#how-venvs-work

вікна,  риба

![image](https://github.com/python/python-docs-uk/assets/3278842/56791085-b419-488a-b201-215fa5d74014)

**Comment by kazanzhy** [comment]
Fixed. Can I ask you to join to Ukrainian team in [Transifex](https://app.transifex.com/python-doc/python-newest)?
It will give you the possibility to make changes faster
