### ISSUE TITLE
transifex-client will stop working on Nov 30

### ISSUE THREAD

**Issue by rffontenelle** [python/python-docs-uk#2]
[transifex-client](https://github.com/transifex/transifex-client/#the-new-client-) uses Transifex APIv2, which will sunset on Nov 30. It was replaced with the new [Transifex CLI tool](https://github.com/transifex/cli#transifex-client). This new tool is written in Go language, so can't be imported in Python scripts.

Alternatives to the deprecated transifex-client are: run the aforementioned CLI tool, use the [transifex-python](https://github.com/transifex/transifex-python) SDK (see [SDK docs](https://developers.transifex.com/reference/api-python-sdk) and the [API reference docs](https://developers.transifex.com/reference/api-introduction)) or use the API directly ­— the [API reference docs](https://developers.transifex.com/reference/api-introduction) has examples written in Python.

**Comment by kazanzhy** [comment]
@rffontenelle thank you for your notification. 
I updated CI/CD pipeline to use a new CLI tool.
